[info]
name = "limine"
version = "1.0.0"
archs = ["x86_64", "aarch64", "riscv64", "loongarch64"]

[source]
repo = "https://github.com/limine-bootloader/limine"
branch = "v8.x"

[build]
script = """
echo "Build: Hello world!"
"""

[install]
script = """
echo "Install: Hello world!"
"""
