use alloc::alloc::AllocError;

/// Encapsulates an Errno value as a result.
pub type EResult<T> = Result<T, Errno>;

#[derive(Debug, PartialEq)]
#[repr(u32)]
pub enum Errno {
    EPERM = uapi::EPERM,
    ENOENT = uapi::ENOENT,
    ESRCH = uapi::ESRCH,
    EINTR = uapi::EINTR,
    EIO = uapi::EIO,
    ENXIO = uapi::ENXIO,
    E2BIG = uapi::E2BIG,
    ENOEXEC = uapi::ENOEXEC,
    EBADF = uapi::EBADF,
    ECHILD = uapi::ECHILD,
    EAGAIN = uapi::EAGAIN,
    ENOMEM = uapi::ENOMEM,
    EACCES = uapi::EACCES,
    EFAULT = uapi::EFAULT,
    ENOTBLK = uapi::ENOTBLK,
    EBUSY = uapi::EBUSY,
    EEXIST = uapi::EEXIST,
    EXDEV = uapi::EXDEV,
    ENODEV = uapi::ENODEV,
    ENOTDIR = uapi::ENOTDIR,
    EISDIR = uapi::EISDIR,
    EINVAL = uapi::EINVAL,
    ENFILE = uapi::ENFILE,
    EMFILE = uapi::EMFILE,
    ENOTTY = uapi::ENOTTY,
    ETXTBSY = uapi::ETXTBSY,
    EFBIG = uapi::EFBIG,
    ENOSPC = uapi::ENOSPC,
    ESPIPE = uapi::ESPIPE,
    EROFS = uapi::EROFS,
    EMLINK = uapi::EMLINK,
    EPIPE = uapi::EPIPE,
    EDOM = uapi::EDOM,
    ERANGE = uapi::ERANGE,
    EDEADLK = uapi::EDEADLK,
    ENAMETOOLONG = uapi::ENAMETOOLONG,
    ENOLCK = uapi::ENOLCK,
    ENOSYS = uapi::ENOSYS,
    ENOTEMPTY = uapi::ENOTEMPTY,
    ELOOP = uapi::ELOOP,
    ENOMSG = uapi::ENOMSG,
    EIDRM = uapi::EIDRM,
    ECHRNG = uapi::ECHRNG,
    EL2NSYNC = uapi::EL2NSYNC,
    EL3HLT = uapi::EL3HLT,
    EL3RST = uapi::EL3RST,
    ELNRNG = uapi::ELNRNG,
    EUNATCH = uapi::EUNATCH,
    ENOCSI = uapi::ENOCSI,
    EL2HLT = uapi::EL2HLT,
    EBADE = uapi::EBADE,
    EBADR = uapi::EBADR,
    EXFULL = uapi::EXFULL,
    ENOANO = uapi::ENOANO,
    EBADRQC = uapi::EBADRQC,
    EBADSLT = uapi::EBADSLT,
    EDEADLOCK = uapi::EDEADLOCK,
    EBFONT = uapi::EBFONT,
    ENOSTR = uapi::ENOSTR,
    ENODATA = uapi::ENODATA,
    ETIME = uapi::ETIME,
    ENOSR = uapi::ENOSR,
    ENONET = uapi::ENONET,
    ENOPKG = uapi::ENOPKG,
    EREMOTE = uapi::EREMOTE,
    ENOLINK = uapi::ENOLINK,
    EADV = uapi::EADV,
    ESRMNT = uapi::ESRMNT,
    ECOMM = uapi::ECOMM,
    EPROTO = uapi::EPROTO,
    EMULTIHOP = uapi::EMULTIHOP,
    EDOTDOT = uapi::EDOTDOT,
    EBADMSG = uapi::EBADMSG,
    EOVERFLOW = uapi::EOVERFLOW,
    ENOTUNIQ = uapi::ENOTUNIQ,
    EBADFD = uapi::EBADFD,
    EREMCHG = uapi::EREMCHG,
    ELIBACC = uapi::ELIBACC,
    ELIBBAD = uapi::ELIBBAD,
    ELIBSCN = uapi::ELIBSCN,
    ELIBMAX = uapi::ELIBMAX,
    ELIBEXEC = uapi::ELIBEXEC,
    EILSEQ = uapi::EILSEQ,
    ERESTART = uapi::ERESTART,
    ESTRPIPE = uapi::ESTRPIPE,
    EUSERS = uapi::EUSERS,
    ENOTSOCK = uapi::ENOTSOCK,
    EDESTADDRREQ = uapi::EDESTADDRREQ,
    EMSGSIZE = uapi::EMSGSIZE,
    EPROTOTYPE = uapi::EPROTOTYPE,
    ENOPROTOOPT = uapi::ENOPROTOOPT,
    EPROTONOSUPPORT = uapi::EPROTONOSUPPORT,
    ESOCKTNOSUPPORT = uapi::ESOCKTNOSUPPORT,
    ENOTSUP = uapi::ENOTSUP,
    EPFNOSUPPORT = uapi::EPFNOSUPPORT,
    EAFNOSUPPORT = uapi::EAFNOSUPPORT,
    EADDRINUSE = uapi::EADDRINUSE,
    EADDRNOTAVAIL = uapi::EADDRNOTAVAIL,
    ENETDOWN = uapi::ENETDOWN,
    ENETUNREACH = uapi::ENETUNREACH,
    ENETRESET = uapi::ENETRESET,
    ECONNABORTED = uapi::ECONNABORTED,
    ECONNRESET = uapi::ECONNRESET,
    ENOBUFS = uapi::ENOBUFS,
    EISCONN = uapi::EISCONN,
    ENOTCONN = uapi::ENOTCONN,
    ESHUTDOWN = uapi::ESHUTDOWN,
    ETOOMANYREFS = uapi::ETOOMANYREFS,
    ETIMEDOUT = uapi::ETIMEDOUT,
    ECONNREFUSED = uapi::ECONNREFUSED,
    EHOSTDOWN = uapi::EHOSTDOWN,
    EHOSTUNREACH = uapi::EHOSTUNREACH,
    EALREADY = uapi::EALREADY,
    EINPROGRESS = uapi::EINPROGRESS,
    ESTALE = uapi::ESTALE,
    EUCLEAN = uapi::EUCLEAN,
    ENOTNAM = uapi::ENOTNAM,
    ENAVAIL = uapi::ENAVAIL,
    EISNAM = uapi::EISNAM,
    EREMOTEIO = uapi::EREMOTEIO,
    EDQUOT = uapi::EDQUOT,
    ENOMEDIUM = uapi::ENOMEDIUM,
    EMEDIUMTYPE = uapi::EMEDIUMTYPE,
    ECANCELED = uapi::ECANCELED,
    ENOKEY = uapi::ENOKEY,
    EKEYEXPIRED = uapi::EKEYEXPIRED,
    EKEYREVOKED = uapi::EKEYREVOKED,
    EKEYREJECTED = uapi::EKEYREJECTED,
    EOWNERDEAD = uapi::EOWNERDEAD,
    ENOTRECOVERABLE = uapi::ENOTRECOVERABLE,
    ERFKILL = uapi::ERFKILL,
    EHWPOISON = uapi::EHWPOISON,
    EIEIO = uapi::EIEIO,
}

// Short form to translate an alloc failure to ENOMEM.
impl From<AllocError> for Errno {
    fn from(_: AllocError) -> Self {
        Errno::ENOMEM
    }
}
