/* A global list of all system calls available. */

#ifndef SYSCALL
#define SYSCALL(num, name, ...)
#endif

SYSCALL(0, exit, int exit)
SYSCALL(1, sigprocmask, int how, const sigset_t* restrict set, sigset_t* restrict oset)
SYSCALL(2, sigsuspend, const sigset_t* sigmask)
SYSCALL(3, sigpending, sigset_t* set)
SYSCALL(4, sigaction, int sig, const struct sigaction* restrict act, struct sigaction* restrict oact)
SYSCALL(6, sigtimedwait, const sigset_t* restrict set, siginfo_t* restrict info,
		const struct timespec* restrict timeout)
SYSCALL(7, mmap, void* addr, size_t len, int prot, int flags, int fildes, off_t off)
SYSCALL(8, munmap, void* addr, size_t len)
SYSCALL(10, mprotect, void* addr, size_t len, int prot)
SYSCALL(11, execve, const char* path, char* const argv[], char* const envp[])
SYSCALL(12, fork, void)
SYSCALL(13, kill, pid_t pid, int sig)
SYSCALL(14, gettid, void)
SYSCALL(15, getpid, void)
SYSCALL(16, waitpid, pid_t pid, int* stat_loc, int options)
SYSCALL(17, read, int fildes, void* buf, size_t nbyte)
SYSCALL(18, write, int fildes, const void* buf, size_t nbyte)
SYSCALL(19, seek, int fildes, off_t offset, int whence)
SYSCALL(20, ioctl, int filedes, unsigned long command, size_t arg)
SYSCALL(21, openat, int fd, const char* path, int oflag, mode_t mode)
SYSCALL(22, close, int fildes)
SYSCALL(23, fstat, int fildes, struct stat* buf)
SYSCALL(24, faccessat, int fd, const char* path, int amode, int flag)
SYSCALL(25, fcntl)
SYSCALL(26, readdir)
SYSCALL(27, getcwd)
SYSCALL(28, chdir)
SYSCALL(29, fchdir)
SYSCALL(30, mkdirat)
SYSCALL(31, rename)
SYSCALL(32, chmodat)
SYSCALL(33, chownat)
SYSCALL(34, linkat)
SYSCALL(35, unlinkat)
SYSCALL(36, readlinkat)
SYSCALL(37, mount)
SYSCALL(38, unmount)
SYSCALL(39, setuid)
SYSCALL(40, getuid)
SYSCALL(41, setgid)
SYSCALL(42, getgid)
SYSCALL(43, umask)
SYSCALL(44, poll)
SYSCALL(45, chroot)
SYSCALL(46, futex_wait)
SYSCALL(47, futex_wake)
SYSCALL(48, socket)
SYSCALL(49, socketpair)
SYSCALL(50, bind)
SYSCALL(51, connect)
SYSCALL(52, accept)
SYSCALL(53, listen)
SYSCALL(54, getpeername)
SYSCALL(55, getsockname)
SYSCALL(56, getsockopt)
SYSCALL(57, setsockopt)
SYSCALL(58, recvmsg)
SYSCALL(59, sendmsg)
SYSCALL(60, sethostname)
SYSCALL(61, uname)
SYSCALL(62, archctl)
SYSCALL(63, readtimer)
SYSCALL(64, savetls)
