#ifndef _MENIX_SYSCALL_NUMBERS_H
#define _MENIX_SYSCALL_NUMBERS_H

#include <menix/compiler.h>

__MENIX_CDECL_START

enum {
    MENIX_SYSCALL_PANIC,
    MENIX_SYSCALL_ARCHCTL,
    MENIX_SYSCALL_LOG,
    MENIX_SYSCALL_HANDLE_VALIDATE,
    MENIX_SYSCALL_HANDLE_DROP,
    MENIX_SYSCALL_HANDLE_CLONE,
    MENIX_SYSCALL_MEM_ALLOC,
    MENIX_SYSCALL_PORT_CREATE,
    MENIX_SYSCALL_PORT_CONNECT,
    MENIX_SYSCALL_PORT_WRITE,
    MENIX_SYSCALL_PORT_READ,
    MENIX_SYSCALL_THREAD_CREATE,
};

__MENIX_CDECL_END

#endif
