#ifndef _MENIX_SYSCALL_NUMBERS_H
#define _MENIX_SYSCALL_NUMBERS_H

enum {
    MENIX_SYSCALL_PANIC = 0,
    MENIX_SYSCALL_ARCHCTL = 1,
    MENIX_SYSCALL_LOG = 2,

    MENIX_SYSCALL_HANDLE_VALIDATE = 3,
    MENIX_SYSCALL_HANDLE_DROP = 4,
    MENIX_SYSCALL_HANDLE_CLONE = 5,

    MENIX_SYSCALL_MEM_ALLOC = 6,

    MENIX_SYSCALL_PORT_CREATE = 7,
    MENIX_SYSCALL_PORT_CONNECT = 8,
    MENIX_SYSCALL_PORT_SEND = 9,
    MENIX_SYSCALL_PORT_RECV = 10,
};

#endif
