#pragma once

enum {
    MENIX_SYSCALL_PANIC,

    MENIX_SYSCALL_LOG,

    MENIX_SYSCALL_ARCHCTL,

    MENIX_SYSCALL_HANDLE_VALIDATE,
    MENIX_SYSCALL_HANDLE_DROP,
    MENIX_SYSCALL_HANDLE_CLONE,

    MENIX_SYSCALL_MEM_ALLOC,
    MENIX_SYSCALL_MEM_FREE,

    MENIX_SYSCALL_PORT_CREATE,
    MENIX_SYSCALL_PORT_CONNECT,
    MENIX_SYSCALL_PORT_ACTION,

    MENIX_SYSCALL_THREAD_CREATE,
    MENIX_SYSCALL_THREAD_DESTROY,
};
