#ifndef _KERNEL_SYS_SYSCALLS_H
#define _KERNEL_SYS_SYSCALLS_H

// TODO
enum {
    SYSCALL_ACTION = 0x80000000,
    SYSCALL_PANIC = 0,
    SYSCALL_LOG,
    SYSCALL_MEMORY_ALLOC,
    SYSCALL_MEMORY_FREE,
    SYSCALL_OBJECT_CHECK,
    SYSCALL_OBJECT_CLOSE,
    SYSCALL_OBJECT_DUPLICATE,
};

#endif
