[package]
name = "initgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
initgraph_proc = { path = "../initgraph_proc" }
intrusive-collections = { version = "0.9.7", features = ["nightly"] }
spin = "0.10.0"
