#ifndef _UAPI_MENIX_ERRNO_H
#define _UAPI_MENIX_ERRNO_H

#define __EPERM			  1
#define __ENOENT		  2
#define __ESRCH			  3
#define __EINTR			  4
#define __EIO			  5
#define __ENXIO			  6
#define __E2BIG			  7
#define __ENOEXEC		  8
#define __EBADF			  9
#define __ECHILD		  10
#define __EAGAIN		  11
#define __ENOMEM		  12
#define __EACCES		  13
#define __EFAULT		  14
#define __ENOTBLK		  15
#define __EBUSY			  16
#define __EEXIST		  17
#define __EXDEV			  18
#define __ENODEV		  19
#define __ENOTDIR		  20
#define __EISDIR		  21
#define __EINVAL		  22
#define __ENFILE		  23
#define __EMFILE		  24
#define __ENOTTY		  25
#define __ETXTBSY		  26
#define __EFBIG			  27
#define __ENOSPC		  28
#define __ESPIPE		  29
#define __EROFS			  30
#define __EMLINK		  31
#define __EPIPE			  32
#define __EDOM			  33
#define __ERANGE		  34
#define __EDEADLK		  35
#define __ENAMETOOLONG	  36
#define __ENOLCK		  37
#define __ENOSYS		  38
#define __ENOTEMPTY		  39
#define __ELOOP			  40
#define __EWOULDBLOCK	  __EAGAIN
#define __ENOMSG		  42
#define __EIDRM			  43
#define __ECHRNG		  44
#define __EL2NSYNC		  45
#define __EL3HLT		  46
#define __EL3RST		  47
#define __ELNRNG		  48
#define __EUNATCH		  49
#define __ENOCSI		  50
#define __EL2HLT		  51
#define __EBADE			  52
#define __EBADR			  53
#define __EXFULL		  54
#define __ENOANO		  55
#define __EBADRQC		  56
#define __EBADSLT		  57
#define __EDEADLOCK		  __EDEADLK
#define __EBFONT		  59
#define __ENOSTR		  60
#define __ENODATA		  61
#define __ETIME			  62
#define __ENOSR			  63
#define __ENONET		  64
#define __ENOPKG		  65
#define __EREMOTE		  66
#define __ENOLINK		  67
#define __EADV			  68
#define __ESRMNT		  69
#define __ECOMM			  70
#define __EPROTO		  71
#define __EMULTIHOP		  72
#define __EDOTDOT		  73
#define __EBADMSG		  74
#define __EOVERFLOW		  75
#define __ENOTUNIQ		  76
#define __EBADFD		  77
#define __EREMCHG		  78
#define __ELIBACC		  79
#define __ELIBBAD		  80
#define __ELIBSCN		  81
#define __ELIBMAX		  82
#define __ELIBEXEC		  83
#define __EILSEQ		  84
#define __ERESTART		  85
#define __ESTRPIPE		  86
#define __EUSERS		  87
#define __ENOTSOCK		  88
#define __EDESTADDRREQ	  89
#define __EMSGSIZE		  90
#define __EPROTOTYPE	  91
#define __ENOPROTOOPT	  92
#define __EPROTONOSUPPORT 93
#define __ESOCKTNOSUPPORT 94
#define __EOPNOTSUPP	  95
#define __ENOTSUP		  __EOPNOTSUPP
#define __EPFNOSUPPORT	  96
#define __EAFNOSUPPORT	  97
#define __EADDRINUSE	  98
#define __EADDRNOTAVAIL	  99
#define __ENETDOWN		  100
#define __ENETUNREACH	  101
#define __ENETRESET		  102
#define __ECONNABORTED	  103
#define __ECONNRESET	  104
#define __ENOBUFS		  105
#define __EISCONN		  106
#define __ENOTCONN		  107
#define __ESHUTDOWN		  108
#define __ETOOMANYREFS	  109
#define __ETIMEDOUT		  110
#define __ECONNREFUSED	  111
#define __EHOSTDOWN		  112
#define __EHOSTUNREACH	  113
#define __EALREADY		  114
#define __EINPROGRESS	  115
#define __ESTALE		  116
#define __EUCLEAN		  117
#define __ENOTNAM		  118
#define __ENAVAIL		  119
#define __EISNAM		  120
#define __EREMOTEIO		  121
#define __EDQUOT		  122
#define __ENOMEDIUM		  123
#define __EMEDIUMTYPE	  124
#define __ECANCELED		  125
#define __ENOKEY		  126
#define __EKEYEXPIRED	  127
#define __EKEYREVOKED	  128
#define __EKEYREJECTED	  129
#define __EOWNERDEAD	  130
#define __ENOTRECOVERABLE 131
#define __ERFKILL		  132
#define __EHWPOISON		  133
#define __EIEIO			  4095

#endif
