# Main part of the build system

message(STATUS "Project license: \"${MENIX_LICENSE}\"")

# Export compile commands.
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Cross-compile flags.
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CROSSCOMPILING TRUE)

set(MENIX_CONFIG ${MENIX_SRC}/include/generated/config.h)
file(WRITE ${MENIX_CONFIG} "#pragma once\n// This file is automatically generated!\n\n")

# Module configuration file.
set(MENIX_MODULES ${MENIX_SRC}/include/generated/exports.h)
file(WRITE ${MENIX_MODULES} "#pragma once\n// This file is automatically generated!\n\n")

# Compile time definitions
message(STATUS "menix v${MENIX_VERSION} (${MENIX_ARCH})")

# Common build arguments
add_compile_options(-Wall -Wno-unused-command-line-argument)
add_link_options(-Wl,--build-id=none)
